# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}

jobs:
  image_scan:
    name: Build Image then Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: dev.Dockerfile
        tags: my-next14-app-demo:latest

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.2.0
      with:
        dockerhub-user: ${{ env.DOCKER_HUB_USERNAME }}
        dockerhub-password: ${{ env.DOCKER_HUB_PAT }}
        command: quickview,cves
        only-severities: critical,high
        exit-code: true
